spring:     
  application:
    name: CRM   #current service name to be used by the eureka server
    
  mongodb:
   embedded:
    version: 5.0.5 
logging:
  level:
    com.quefi.authentication: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web: DEBUG
  file: logs/crm.log  
tpd:
  appconfig:    
    proxy: proxy
    port : 9001
    mailManager: mailmanager  
  