spring:     
  datasource:
    url:  jdbc:mysql://localhost:3307/users 
    username: root
    password: adminadmin
  jpa:
    hibernate.ddl-auto: update
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect


 
logging:
  level:
    com.quefi.authentication: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web: DEBUG
  file: logs/crm.log  
tpd:
  appconfig:    
    proxy: proxy
    port : 9001
    mailManager: mailmanager  
  